[project]
name = "langgraph-tutorial-wenwenc9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "dotenv>=0.4.38",
    "grandalf>=0.8",
    "jupyterlab>=4.4.9",
    "langchain>=0.3.27",
    "langchain-community>=0.3.31",
    "langchain-milvus>=0.2.2",
    "langchain-openai>=0.3.35",
    "langgraph>=0.6.10",
    "langgraph-checkpoint-postgres>=3.0.1",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "openpyxl>=3.1.5",
    "rich>=14.2.0",
    "tomlkit>=0.13.3",
    "volcengine>=1.0.205",
]
